# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release Maven Package

on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          generate_release_notes: true
          token: ${{ secrets.TOKEN_TECH }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github

      - name: Publish
        run: |
          mvn --batch-mode deploy -Darguments=-DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_TECH }}